# Generated by Django 3.1.3 on 2020-12-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseid', models.AutoField(db_column='caseId', primary_key=True, serialize=False)),
                ('casename', models.CharField(db_column='caseName', max_length=255)),
                ('casescripts', models.CharField(db_column='caseScripts', max_length=255)),
                ('caseowner', models.CharField(db_column='caseOwner', max_length=255)),
                ('casefr', models.CharField(db_column='caseFR', max_length=255)),
                ('casetime', models.DateTimeField(db_column='caseTime')),
            ],
            options={
                'db_table': 'case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('jobid', models.IntegerField(db_column='jobId', primary_key=True, serialize=False)),
                ('suite', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('jobowner', models.CharField(db_column='jobOwner', max_length=255)),
                ('bugid', models.CharField(blank=True, db_column='bugId', max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('suiteid', models.AutoField(db_column='suiteId', primary_key=True, serialize=False)),
                ('suitename', models.CharField(db_column='suiteName', max_length=255)),
                ('suiteowner', models.CharField(db_column='suiteOwner', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('suitecase', models.TextField(db_column='suiteCase')),
            ],
            options={
                'db_table': 'suite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atxTest.case')),
            ],
            options={
                'db_table': 'parameters',
                'managed': True,
            },
        ),
    ]
