# Generated by Django 3.1.3 on 2020-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atxTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.CharField(max_length=255, verbose_name='suite')),
                ('device', models.CharField(max_length=255, verbose_name='device')),
                ('flag', models.IntegerField(verbose_name='flag')),
            ],
            options={
                'db_table': 'execute',
                'managed': True,
            },
        ),
    ]
